FRONTENDSCHOOL8/dream8

package-lock.json
package.json
tsconfig.json
vite.config.ts

[초기설정] 배포테스트 taewook
어떤 변경 사항이 있나요?

[초기설정] 배포테스트 taewook

---

README.md

[초기설정] 배포 테스트 taewook
어떤 변경 사항이 있나요?

[초기설정] 배포 테스트 taewook

---

README.md

[초기설정 ]Featuer/initial test taewook
어떤 변경 사항이 있나요?

[초기설정 ]Featuer/initial test taewook

---

tailwind.config.js

[Feat] :	새로운 기능 추가
[Modify] :	코드 변경
[BugFix] :	버그 수정
[Comment] :	필요한 주석 추가 및 변경
[Docs] :	문서의 수정
[Refactor] :	리팩토링
[Design] :	CSS 등 사용자 UI 디자인 변경
[Style] :	코드 포맷팅, 세미콜론 누락, 코드 변경이 없는 경우
[Test] :	테스트(테스트 코드 추가, 수정, 삭제, 비즈니스 로직에 변경이 없는 경우)
[Chore] :	빌드 수정, 패키지 매니저 설정, 운영 코드 변경이 없는 경우(assets image, 패키지 매니저 등)
[Init] :	프로젝트 초기 생성
[Rename] :	파일 혹은 폴더명 수정하거나 옮기는 경우
[Remove] :	파일을 삭제하는 작업만 수행하는 경우
[Merge] :	Pull 과정 중 현재 commit과 자동 병합이 일어날 때
[Build] :	새로운 라이브러리 혹은 패키지
어떤 변경 사항이 있나요?
- 테마 색상 지정 했습니당

[Style] : 테미 컬러 작성 (현돈: 11:17)

---

src/routes/navigation.tsx
src/routes/routingStart.tsx

[Feat] : src/routes/navigation.tsx lazy 로더 수정 taewook 11:49
어떤 변경 사항이 있나요?

[Feat] : src/routes/navigation.tsx lazy 로더 수정 taewook 11:49

---

src/routes/navigation.tsx

코드 변경src/routes/navigation.tsx News변경 taewook 14:00
어떤 변경 사항이 있나요?

[Modify] :    코드 변경src/routes/navigation.tsx News변경 taewook 14:00

---

src/components/Footer/Footer.tsx

modified:   src/components/Footer/Footer.tsx
Footer CSS 등 사용자 UI 디자인 변경 tawook 14:44
#35 
어떤 변경 사항이 있나요?

[Design] :   Footer CSS 등 사용자 UI 디자인 변경 tawook 14:44

---

src/components/Header/Header.tsx
src/pages/Login/SignIn/atoms/SignInFormInput.stories.tsx
src/pages/Login/SignIn/atoms/SignInFormInput.tsx
src/pages/Login/SignIn/atoms/SignInFormLogin.tsx
src/pages/Login/SignIn/atoms/SocialLoginButton.tsx
src/pages/Login/SignIn/atoms/SocialLoginImage.tsx
src/pages/Login/SignIn/atoms/SocialLoginSpan.tsx
src/pages/Login/SignIn/molecules/SignInForm.tsx
src/pages/Login/SignIn/molecules/SocialButtonMolecules.tsx
src/pages/Login/SignIn/organisms/SocialLoginButtons.tsx
src/pages/Login/SignIn/page/SignIn.tsx
src/pages/Login/SignIn/templates/SignInTemplates.tsx
src/store/useLoginFormStore.ts

[Feat] : 로그인 스토리북 작성중 taewook 13:26
어떤 변경 사항이 있나요?

[Feat] : 로그인 스토리북 작성중 taewook 13:26

---

src/pages/Exchange/page/Exchange/Exchange.tsx

[Feat] : 교환 메인 페이지 로그인 여부에 따라 수정(현돈: 14:51)

---

src/components/01_atoms/Button/Button.tsx
src/components/01_atoms/Input/Input.tsx
src/components/Input/InputTextArea.tsx

[Modify] :  Atoms 수정  taewook 15:55
#
#	new file:   src/components/01_atoms/Button/Button.tsx
#	deleted:    src/components/01_atoms/Button/sdf
#	new file:   src/components/01_atoms/Input/Input.tsx
#	deleted:    src/components/01_atoms/Input/sdf
#	deleted:    src/components/Input/InputTextArea.tsx
#	deleted:    src/pages/Login/SignIn/page/SignIn.stories.tsx
#
어떤 변경 사항이 있나요?

[Modify] :  Atoms 수정  taewook 15:55

---

src/components/01_atoms/Input/Input.tsx
src/components/01_atoms/Product/Cautions.tsx
src/components/02_molecules/Modal/CautionModal/CautionModal.tsx
src/components/02_molecules/Modal/ConfirmModal/ConfirmModal.tsx
src/components/02_molecules/Modal/SelectModal/SelectModal.tsx
src/components/02_molecules/Product/ListProduct/ListProduct.tsx
src/components/03_organisms/Product/ArrangeProduct/ArrangeProduct.tsx
src/components/03_organisms/Product/CategoryProduct/CategoryProduct.tsx
src/components/03_organisms/Product/ListsProduct/ListsProduct.tsx
src/components/03_organisms/Product/MyCartList/MyCartList.tsx
src/components/03_organisms/Product/SearchProduct/SearchProduct.tsx
src/components/05_pages/Product/Payment/Payment.tsx
src/components/05_pages/Product/Product/Product.tsx
src/components/05_pages/Product/ProductDetails/ProductDetails.tsx
src/routes/navigation.tsx

[Refactor] : 코드 폴더 구성 리펙토링 (서린 - 16:32)

---

src/components/01_atoms/Image/Image.tsx

[Feat] : 이미지 atom으로 분리해서 컴포넌트 생성(현돈: 16:53)

---

src/components/01_atoms/Button/Button.tsx
src/components/02_molecules/Modal/ConfirmModal/ConfirmModal.tsx
src/components/02_molecules/Modal/SelectModal/SelectModal.tsx
src/components/05_pages/Product/Payment/Payment.tsx
src/components/05_pages/Product/ProductDetails/ProductDetails.tsx

[Refactor] : 모달 버튼 컴포넌트 적용, 버튼 컴포넌트 수정 (서린 - 17:28)

---

.storybook/preview.ts
src/components/01_atoms/Button/Button.stories.tsx
src/components/01_atoms/Button/Button01.stories.tsx
src/components/01_atoms/Button/Button01.tsx
src/components/01_atoms/Image/Image.tsx
src/components/01_atoms/Input/Input.tsx
src/components/02_molecules/Mypage/CategoryMolecules.tsx
src/components/02_molecules/Mypage/MypageInfoMolecules.stories.tsx
src/components/02_molecules/Mypage/MypageInfoMolecules.tsx
src/components/02_molecules/Mypage/MypageInfoUserCard.stories.tsx
src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
src/components/02_molecules/SignIn/SignInForm.stories.tsx
src/components/02_molecules/SignIn/SignInForm.tsx
src/components/02_molecules/SignIn/SocialButtonMolecules.tsx
src/components/03_organisms/Header/GlobalNavBar.tsx
src/components/03_organisms/Header/Header.tsx
src/components/03_organisms/Mypage/MypageOrganisms.tsx
src/components/03_organisms/SignIn/SocialLoginButtons.stories.tsx
src/components/03_organisms/SignIn/SocialLoginButtons.tsx
src/components/04_templates/SignIn/SignInTemplates.stories.tsx
src/components/04_templates/SignIn/SignInTemplates.tsx
src/components/05_pages/Mypage/MyPage.tsx
src/components/05_pages/SignIn/SignIn.tsx
src/styles/tailwindcss.css
tailwind.config.js

[Feat] : Button01컴포넌트, 마이페이지, 스토리북 taewook 18:10
1. tailwindcss.css,  tailwind.config.js , button01 컴포넌트 수정 (추후 기존button으로 전환), 스토리북 적용
어떤 변경 사항이 있나요?

[Feat] : Button01컴포넌트, 마이페이지, 스토리북 taewook 18:10

---

src/components/02_molecules/SignIn/SignInForm.tsx
src/components/05_pages/Donation/Donation/Donation.tsx
src/store/useLoginFormStore.ts

[Feat] : 로그인한 유저 정보 전역상태에 넣기  taewook 19:31
어떤 변경 사항이 있나요?

[Feat] : 로그인한 유저 정보 taewook 19:31

---

src/components/03_organisms/Product/ArrangeProduct/ArrangeProduct.tsx
src/components/03_organisms/Product/CategoryProduct/CategoryProduct.tsx
src/components/05_pages/Product/Product/Product.tsx
src/components/05_pages/Product/ProductDetails/ProductDetails.tsx
src/routes/navigation.tsx

Feature/product  - 판매, 판매 상세 페이지의 loader, useQuery  적용 , 판매페이지 디자인 수정

---

src/components/04_templates/Donation/DonationContent.tsx
src/components/05_pages/News/News/News.tsx
src/components/05_pages/News/NewsDetails/NewsDetails.tsx
src/routes/navigation.tsx

news detail 페이지 구성
어떤 변경 사항이 있나요?

news detail 페이지 구성

---

src/components/02_molecules/Product/ListProduct/ListProduct.tsx
src/components/03_organisms/Product/ArrangeProduct/ArrangeProduct.tsx
src/components/03_organisms/Product/ListsProduct/ListsProduct.tsx
src/components/04_templates/ProductDetails/ProductDetailsInfo/ProductDetailsInfo.tsx
src/components/05_pages/Product/Payment/Payment.tsx
src/components/05_pages/Product/Product/Product.tsx
src/components/05_pages/Product/ProductDetails/ProductDetails.tsx

Feature/product 판매페이지 정렬기능

---

src/components/02_molecules/Mypage/CategoryMolecules.tsx
src/components/02_molecules/Mypage/MypageInfoMolecules.tsx
src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
src/components/02_molecules/SignIn/SignInForm.tsx
src/components/03_organisms/Header/Header.tsx
src/components/03_organisms/Mypage/MypageOrganisms.tsx
src/components/03_organisms/SignIn/SocialLoginButtons.tsx
src/components/04_templates/SignIn/SignInTemplates.tsx
src/components/05_pages/Donation/Donation/Donation.tsx
src/store/useLoginFormStore.ts
src/styles/tailwindcss.css

[Feat] : 회원가입,마이페이지,로그인 여부 표시, 마이페이지 수정, 전역상태값 새로고침 수정 taewook 16:35
어떤 변경 사항이 있나요?

[Feat] : 회원가입,마이페이지,로그인 여부 표시, 마이페이지 수정, 전역상태값 새로고침 수정 태욱16:35

---

package-lock.json
package.json
src/components/01_atoms/Input/Input.tsx
src/components/02_molecules/Mypage/MypageInfoMolecules.tsx
src/components/02_molecules/SignIn/SignInForm.tsx
src/components/02_molecules/SignUp/SignUpInput.tsx
src/components/03_organisms/Header/Header.tsx
src/components/03_organisms/Header/Logout.tsx
src/store/useLoginFormStore.ts
src/utils/formatphoneNumber.ts

[Feat] : 회원탈퇴+전역상태값 계속유지+ 로그아웃 + 주소검색 태욱 23:49
어떤 변경 사항이 있나요?

 [Feat] : 회원탈퇴+전역상태값 계속유지+ 로그아웃 + 주소검색 태욱 23:49

---

src/components/02_molecules/Mypage/MypageUserSetting.tsx
src/components/02_molecules/Mypage/components/TransactionListCard.tsx
src/utils/formatphoneNumber.ts

[Feat] : 2 formatPhoneNumber 수정 , 거래내역, 후원내역 태욱 18:30
어떤 변경 사항이 있나요?

[Feat] : 2 formatPhoneNumber 수정 , 거래내역, 후원내역 태욱 18:30

---

src/utils/formatphoneNumber.ts

[modify]: 파일 이름 변경  src/utils/formatphoneNumber.ts 태욱
어떤 변경 사항이 있나요?

[modify]: 파일 이름 변경  src/utils/formatphoneNumber.ts 태욱

---

src/components/02_molecules/Mypage/MypageUserSetting.tsx

[Modify] :    코드 변경 '@/utils/formatphoneNumber' 대소문자 태욱
어떤 변경 사항이 있나요?

[Modify] :    코드 변경 '@/utils/formatphoneNumber' 대소문자 태욱

---

package-lock.json
src/components/02_molecules/Modal/ConfirmModal/ConfirmModal.tsx
src/components/02_molecules/Modal/SelectModal/SelectModal.tsx
src/components/03_organisms/Product/ListsProduct/ListsProduct.tsx
src/components/03_organisms/ProductDetails/RelativeProducts/RelativeProducts.tsx
src/components/04_templates/ProductDetails/ProductDetailsInfo/ProductDetailsInfo.tsx
src/components/05_pages/Product/Payment/Payment.tsx

[Modify] : 모달창 z-index 변경 - 서린(10:04)

---

package-lock.json
package.json
src/components/04_templates/Donation/DonationContent.tsx
src/components/04_templates/Home/HomeContents.tsx
src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
src/components/05_pages/News/News/News.tsx
src/components/05_pages/News/NewsDetails/NewsDetails.tsx

gsap 설치 플러그인 설치, gsap 애니메이션 적용 (Home) 
donation, news 페이지 px -> rem으로 수정
어떤 변경 사항이 있나요?

gsap 설치, gsap 애니메이션 적용 (Home) 서윤(18:12)

---

src/components/01_atoms/Cautions/Cautions.stories.tsx
src/components/01_atoms/Cautions/Cautions.tsx
src/components/01_atoms/Divider/Divider.stories.tsx
src/components/02_molecules/Modal/CautionModal/CautionModal.stories.tsx
src/components/02_molecules/Modal/CautionModal/CautionModal.tsx
src/components/02_molecules/Modal/ConfirmModal/ConfirmModal.stories.tsx
src/components/02_molecules/Modal/SelectModal/SelectModal.stories.tsx
src/components/03_organisms/Product/CategoryProduct/CategoryProduct.tsx
src/components/03_organisms/Product/ListsProduct/ListsProduct.tsx
src/components/05_pages/Product/Product/Product.tsx
src/components/05_pages/Product/ProductDetails/ProductDetails.tsx
src/hooks/useModal.ts

Feature/product  useModal 훅 생성과 적용, 스토리북 생성

---

package-lock.json
src/api/pocketbase.ts
src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
src/components/02_molecules/Mypage/MypageUserSetting.tsx
src/components/03_organisms/Header/GlobalNavBar.tsx
src/components/03_organisms/Header/Notification/NotificationCommon.tsx
src/components/03_organisms/Header/Notification/components/CommonLayout.tsx
src/components/03_organisms/SignIn/SocialLoginButtons.tsx
src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
src/components/05_pages/Product/Payment/Payment.tsx
src/features/SnsService/KakaoRedirect.tsx
src/store/useLoginFormStore.ts
src/store/useNoticeList.ts

[Feat] : 장바구니 Payment에 notification DB에 생성 태욱 11:28
어떤 변경 사항이 있나요?

[Feat] : 장바구니 Payment에 notification DB에 생성 태욱 11:28

---

public/arrow-up.svg
src/components/01_atoms/GoToTop/GoToTop.tsx
src/components/01_atoms/News/NewsList/NewsList.tsx
src/components/03_organisms/Home/NewsCard.tsx
src/components/04_templates/Donation/DonationContent.tsx
src/components/04_templates/Home/HomeContents.tsx
src/components/05_pages/Donation/Donation/Donation.tsx
src/components/05_pages/News/News/News.tsx
src/layout/RootLayout.tsx

TopScroll 구현 서윤
어떤 변경 사항이 있나요?

TopScroll 구현 서윤(11:30)

---

src/components/03_organisms/Header/GlobalNavBar.tsx
src/components/03_organisms/Header/Notification/NotificationCommon.tsx
src/components/03_organisms/Header/Notification/components/CommonLayout.tsx
src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
src/components/05_pages/Product/Payment/Payment.tsx

[Feat] :  일반알림 -  판매, 후원 구현 record type추가  태욱 13:28
어떤 변경 사항이 있나요?

[Feat] :  일반알림 -  판매, 후원 구현 record type추가  태욱 13:28

---

src/components/02_molecules/Home/Dots.tsx

Dots z-index 수정
어떤 변경 사항이 있나요?

Dots z-index 수정 서윤(13:53)

---

src/components/02_molecules/Modal/ConfirmModal/ConfirmModal.tsx
src/components/02_molecules/Modal/SelectModal/SelectModal.tsx
src/components/03_organisms/Payment/MyCartList/MyCartList.tsx

Feature/product 모달창 focus block

---

src/components/01_atoms/GoToTop/GoToTop.tsx
src/components/03_organisms/Donation/DonationForm/DonationForm.tsx
src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx

Donation 데이터 중복 저장 수정, css 수정
어떤 변경 사항이 있나요?

Donation 데이터 중복 저장 수정

---

src/components/03_organisms/Header/Header.tsx
src/components/04_templates/Donation/DonationContent.tsx
src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
src/components/05_pages/News/News/News.tsx
src/components/05_pages/News/NewsDetails/NewsDetails.tsx
src/layout/RootLayout.tsx

Header등 padding값 수정 (서윤 15:43)
어떤 변경 사항이 있나요?

Header등 padding값 수정 (서윤 15:43)

---

src/components/03_organisms/Footer/Footer.tsx
src/components/03_organisms/Header/Header.tsx
src/components/05_pages/Product/Product/Product.tsx

[Design] :  header foot px 변경 - 서린 (16:25)

---

src/components/01_atoms/GoToTop/GoToTop.tsx

[Design] :   GotoTop padding 위치 조정 - 서린 (16:53)

---

src/components/03_organisms/Payment/MyCartList/MyCartList.tsx
src/components/05_pages/Product/Payment/Payment.tsx

Feature/product import, 코드 정리

---

src/components/05_pages/Donation/Donation/Donation.tsx
src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
src/components/05_pages/Home/Home.tsx
src/components/05_pages/News/News/News.tsx
src/components/05_pages/News/NewsDetails/NewsDetails.tsx

meta 태그 추가 서윤

---

package-lock.json
package.json

[Build] :  2차 배포 빌드 태욱
어떤 변경 사항이 있나요?

[Build] :  2차 배포 빌드 태욱

---

src/components/04_templates/Home/HomeContents.tsx

[Comment] :  주석삭제 (서윤 9:40)
어떤 변경 사항이 있나요?

[Comment] :  주석삭제 (서윤 9:40)

---

vercel.json

[BugFix] :  Vercel 배포 시, 페이지를 못 찾는 문제 해결 - 서린 (11:41)

---

src/components/02_molecules/Exchange/ExchangeCard/ExchangeCard.tsx
src/components/02_molecules/Exchange/User/User.tsx
src/components/05_pages/Exchange/Exchange.tsx
src/styles/tailwindcss.css

[Design] :  교환페이지 css 수정 (서윤 14:07)

---

src/components/02_molecules/Mypage/CategoryMolecules.tsx
src/components/02_molecules/Mypage/MypageExchange.tsx
src/components/02_molecules/Mypage/MypageInfoUserCard.tsx
src/components/02_molecules/Mypage/MypageSponsorship.tsx
src/components/02_molecules/Mypage/MypageTransaction.tsx
src/components/02_molecules/SignUp/SignUpInput.tsx
src/components/03_organisms/Header/Notification/NotificationCommon.tsx
src/components/03_organisms/Header/Notification/components/LoginCheckLayout.tsx
src/components/03_organisms/Header/Notification/components/NothingNotification.tsx

[Modify] : 회원가입후 로그인으로이동, skipToContent a태그유지, 카테고리click시 색깔표시, 알림창고정값, 알림없음표시, 비로그인시 로그인하기 이동추가, 마이페이지 내역 3개 미만일 때 더보기 안보이기   태욱
어떤 변경 사항이 있나요?

[Modify] : 회원가입후 로그인으로이동, skipToContent a태그유지, 카테고리click시 색깔표시, 알림창고정값, 알림없음표시, 비로그인시 로그인하기 이동추가, 마이페이지 내역 3개 미만일 때 더보기 안보이기   태욱

---

src/components/05_pages/Exchange/ExchangeWrite.tsx
src/components/Button/SubmitButton.tsx

Feature/product 교환신청 폼 디자인 변경

---

src/components/02_molecules/Exchange/ExchangeCard/ExchangeCard.tsx
src/components/05_pages/Exchange/Exchange.tsx

[Design] : 교환 메인 페이지 게시글 작성 버튼 수정(현돈: 14:39)

---

src/components/05_pages/Exchange/ExchangeDetail.tsx
src/components/05_pages/Exchange/ExchangeWrite.tsx

[Design] : 교환 디테일 디자인 수정(현돈: 15:02)

---

tailwind.config.js

[Feat] :   브레이크포인트 설정 - 서린(10:13)

---

src/components/03_organisms/Header/Header.tsx

[BugFix] :  헤더 스타일 버그 수정 태욱
어떤 변경 사항이 있나요?

[BugFix] :  헤더 스타일 버그 수정 태욱

---

src/components/02_molecules/Mypage/CategoryMolecules.tsx
src/components/02_molecules/Mypage/MypageUserSetting.tsx
src/components/05_pages/Donation/DonationSubmission/DonationSubmission.tsx
src/components/05_pages/Mypage/Mypage.tsx
src/components/05_pages/News/NewsDetails/NewsDetails.tsx
tailwind.config.js

[BugFix] : 소식페이지, 마이페이지 수정 반응형 태욱

---

src/components/03_organisms/Header/Notification/NotificationCommon.tsx
src/components/03_organisms/Header/Notification/components/CommonLayout.tsx

[Modify] : 알림창 수정 반응형  태욱

---

src/components/04_templates/Home/HomeContents.tsx

[BugFix] 모바일웹에서는 메인화면 스크롤 안되는 수정중  태욱

---

src/components/04_templates/Home/HomeContents.tsx
src/styles/tailwindcss.css

[BugFix] : 모바일에서 메인화면 스크롤 먹통 수정 태욱
